package com.rila13.hibernate.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the films table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="films"
 */
public abstract class BaseFilms  implements Serializable {

	public static String PROP_TITRE_FILM = "TitreFilm";
	public static String PROP_CODE_FILM = "CodeFilm";
	public static String PROP_ANNEE_FILM = "AnneeFilm";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _codeFilm;

	// fields
	private java.lang.String _titreFilm;
	private java.lang.Integer _anneeFilm;

	// collections
	private java.util.Set _joueSet;


	// constructors
	public BaseFilms () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseFilms (java.lang.Integer _codeFilm) {
		this.setCodeFilm(_codeFilm);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseFilms (
		java.lang.Integer _codeFilm,
		java.lang.String _titreFilm,
		java.lang.Integer _anneeFilm) {

		this.setCodeFilm(_codeFilm);
		this.setTitreFilm(_titreFilm);
		this.setAnneeFilm(_anneeFilm);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="vm"
     *  column="codeFilm"
     */
	public java.lang.Integer getCodeFilm () {
		return _codeFilm;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _codeFilm the new ID
	 */
	public void setCodeFilm (java.lang.Integer _codeFilm) {
		this._codeFilm = _codeFilm;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: titreFilm
	 */
	public java.lang.String getTitreFilm () {
		return _titreFilm;
	}

	/**
	 * Set the value related to the column: titreFilm
	 * @param _titreFilm the titreFilm value
	 */
	public void setTitreFilm (java.lang.String _titreFilm) {
		this._titreFilm = _titreFilm;
	}


	/**
	 * Return the value associated with the column: anneeFilm
	 */
	public java.lang.Integer getAnneeFilm () {
		return _anneeFilm;
	}

	/**
	 * Set the value related to the column: anneeFilm
	 * @param _anneeFilm the anneeFilm value
	 */
	public void setAnneeFilm (java.lang.Integer _anneeFilm) {
		this._anneeFilm = _anneeFilm;
	}


	/**
	 * Return the value associated with the column: JoueSet
	 */
	public java.util.Set getJoueSet () {
		return this._joueSet;
	}

	/**
	 * Set the value related to the column: JoueSet
	 * @param _joueSet the JoueSet value
	 */
	public void setJoueSet (java.util.Set _joueSet) {
		this._joueSet = _joueSet;
	}
	
	public void addToJoueSet (Object obj) {
		if (null == this._joueSet) this._joueSet = new java.util.HashSet();
		this._joueSet.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof com.rila13.hibernate.base.BaseFilms)) return false;
		else {
			com.rila13.hibernate.base.BaseFilms mObj = (com.rila13.hibernate.base.BaseFilms) obj;
			if (null == this.getCodeFilm() || null == mObj.getCodeFilm()) return false;
			else return (this.getCodeFilm().equals(mObj.getCodeFilm()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getCodeFilm()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getCodeFilm().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}