package com.rila13.hibernate.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the joue table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="joue"
 */
public abstract class BaseJoue  implements Serializable {

	public static String PROP_ID = "Id";
	public static String PROP_CASTING = "Casting";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private com.rila13.hibernate.JouePK _id;

	// fields
	private java.lang.String _casting;


	// constructors
	public BaseJoue () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseJoue (com.rila13.hibernate.JouePK _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseJoue (
		com.rila13.hibernate.JouePK _id,
		java.lang.String _casting) {

		this.setId(_id);
		this.setCasting(_casting);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     */
	public com.rila13.hibernate.JouePK getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (com.rila13.hibernate.JouePK _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: casting
	 */
	public java.lang.String getCasting () {
		return _casting;
	}

	/**
	 * Set the value related to the column: casting
	 * @param _casting the casting value
	 */
	public void setCasting (java.lang.String _casting) {
		this._casting = _casting;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof com.rila13.hibernate.base.BaseJoue)) return false;
		else {
			com.rila13.hibernate.base.BaseJoue mObj = (com.rila13.hibernate.base.BaseJoue) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}